// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1J0pef8YmyJWmPoPCXGk4osATPCXkf3I',
    appId: '1:12988237571:web:2d6065b424c6b60fd74b36',
    messagingSenderId: '12988237571',
    projectId: 'campusflow-fcf50',
    authDomain: 'campusflow-fcf50.firebaseapp.com',
    storageBucket: 'campusflow-fcf50.firebasestorage.app',
    measurementId: 'G-TQXEMDQVJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1ZZIPYv2LzF9q-PbRtsrfyTbSlxvg6ps',
    appId: '1:12988237571:android:cec148ad9e07dd68d74b36',
    messagingSenderId: '12988237571',
    projectId: 'campusflow-fcf50',
    storageBucket: 'campusflow-fcf50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuwHT_8ifCSGpojUQcz8AcO6IfUHHyge0',
    appId: '1:12988237571:ios:fd6a55dc4bfca31ad74b36',
    messagingSenderId: '12988237571',
    projectId: 'campusflow-fcf50',
    storageBucket: 'campusflow-fcf50.firebasestorage.app',
    iosBundleId: 'com.campusflow.campusflow',
  );
}
